# Configuración del Makefile
PYTHON = python3  # Comando para ejecutar Python
MAIN_FILE = main.py  # Nombre del archivo principal

.PHONY: run

# Regla para compilar y ejecutar el programa
run:
	$(PYTHON) $(CURDIR)/$(MAIN_FILE)
